### ISSUE TITLE
Generate Mesh (Step 1) --  FAILED

### ISSUE THREAD

**Issue by HEUMK** [Spationaute/SuperMarine#1]
Hello,I try to run the example in OF5.x by python3 setup.py,but fail.

**Comment by Spationaute** [comment]
I tested it on OF6 and right now its ready for OF7. It might be some difference in configuration file. Can you send me the error? I'll try to fix the script for you.

**Comment by HEUMK** [comment]
Traceback (most recent call last):
  File "./superMarine-0.3b.py", line 51, in <module>
    import numpy as np
ImportError: No module named 'numpy'

***************that is the err.log  Thanks

**Comment by Spationaute** [comment]
This error tell that you dont have numpy (a python module) installed on your system. To install it, if you are on ubuntu, you call call `pip3 install numpy` in the console.

Its a bug in my readme I should put the dependency! 

Thanks alot!

**Comment by Spationaute** [comment]
I fixed the **readme**. I'll close this issue, if you run in another bug or need help you can open another issue.
